---
title: "QA Guidelines"
author: "Suggestions/DRAFT for DINA TC"
date: "April 5, 2016"
output: 
  html_document:
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following are RECOMMENDED guidelines for QA (quality assurance) of DINA-Web modules.

# Summary

Checks:

  - Check that sources are available openly under acceptable license - take a note of GitHub (or equiv.) URL
  - Check that repo shows Green badge for building with Travis CI
  - Check that semantic versioning used - take a note of the version nr
  - Check that Tests are OK
  - Check that Vignette / Turorial / README.md - documentation is provided that explains the module and its usage - take a note of the URL
  - Check that API documentation exists if the module exposes an API - take a note of the URL
  
  - Determine Accessibility Guidelines compliance by running tools and looking at results
  - Determine Security OWASP compliance by running tools and looking at results
  - Determine performance/scalability compliance by running load testing tools

# QA Pass or Fail actions
  
If checks fail, provide results to the module maintainer and kindly ask for specific issues to be fixed. Register issues on relevant repo along with discovered details.

If checks pass then Announce the release passing QA checks to the mailing list and bundle it into integration projects.

# QA Tools

## Tools for checking Web Accessibility compliance

  - Ask G N for up-to-date recommendation

## Tools for checking security compliance

  - Ask G N for up-to-date recommendation

## Tools for load testing / stress testing

  - loader.io (online service)
  - offline tools ?
  
  